name: "Mark or close stale issues and PRs"

on:
  workflow_call:
    inputs:
      days-before-stale:
        description: "Number of days before marking issues/PRs as stale"
        required: false
        type: number
        default: 30
      days-before-close:
        description: "Number of days before closing stale issues/PRs"
        required: false
        type: number
        default: 10

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v10.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Staling issues and PR's
          days-before-stale: ${{ inputs.days-before-stale }}
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open ${{ inputs.days-before-stale }} days
            with no activity. Remove stale label or comment or this issue will be closed in ${{ inputs.days-before-close }} days
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open ${{ inputs.days-before-stale }} days
            with no activity. Remove stale label or comment or this PR will be closed in ${{ inputs.days-before-close }} days
          # Not stale if have this labels or part of milestone
          exempt-issue-labels: bug,wip,on-hold
          exempt-pr-labels: bug,wip,on-hold
          exempt-all-milestones: true
          # Close issue operations
          # Label will be automatically removed if the issues are no longer closed nor locked.
          days-before-close: ${{ inputs.days-before-close }}
          delete-branch: true
          close-issue-message: This issue was automatically closed because of stale in ${{ inputs.days-before-close }} days
          close-pr-message: This PR was automatically closed because of stale in ${{ inputs.days-before-close }} days
